# Generated by Django 2.2.1 on 2019-05-25 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=120)),
                ('Rated', models.CharField(max_length=120)),
                ('Released', models.CharField(max_length=120)),
                ('Runtime', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('Director', models.CharField(max_length=120)),
                ('Writer', models.CharField(max_length=120)),
                ('Actors', models.CharField(max_length=120)),
                ('Plot', models.TextField()),
                ('Language', models.CharField(max_length=120)),
                ('Country', models.CharField(max_length=120)),
                ('Awards', models.CharField(max_length=250)),
                ('Poster', models.URLField()),
                ('Ratings', models.TextField()),
                ('Metascore', models.CharField(max_length=120)),
                ('imdbRating', models.CharField(max_length=120)),
                ('imdbVotes', models.CharField(max_length=120)),
                ('imdbID', models.CharField(max_length=120)),
                ('Type', models.CharField(max_length=120)),
                ('totalSeasons', models.CharField(max_length=120)),
                ('DVD', models.CharField(max_length=120)),
                ('BoxOffice', models.CharField(max_length=120)),
                ('Production', models.CharField(max_length=120)),
                ('Website', models.URLField()),
                ('Response', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie_api.Movie')),
            ],
        ),
    ]
